* The settings a program turns on and off around a piece of work and then puts back. Most of
* them have nothing to act on here - one process rather than a network, a window rather than a
* screen of characters, no printer - but SET() has to report every one of them, because that is
* how a program saves a setting and restores it.
SET ANSI ON
? SET("ANSI")
SET ANSI OFF
? SET("ANSI")
SET AUTOINCERROR OFF
? SET("AUTOINCERROR")
SET AUTOSAVE ON
? SET("AUTOSAVE")
SET BELL OFF
? SET("BELL")
SET BROWSEIME ON
? SET("BROWSEIME")
SET BRSTATUS ON
? SET("BRSTATUS")
SET CLEAR OFF
? SET("CLEAR")
SET CLOCK ON
? SET("CLOCK")
SET COMPATIBLE ON
? SET("COMPATIBLE")
SET COMPATIBLE OFF
SET CONFIRM ON
? SET("CONFIRM")
SET CONSOLE ON
? SET("CONSOLE")
SET CONSOLE OFF
SET CPDIALOG OFF
? SET("CPDIALOG")
SET CURSOR OFF
? SET("CURSOR")
SET DELIMITERS ON
? SET("DELIMITERS")
SET DELIMITERS OFF
SET DEVELOPMENT OFF
? SET("DEVELOPMENT")
SET DOHISTORY ON
? SET("DOHISTORY")
* event tracking stays off until an event list names what to track, so ON is not on
SET EVENTTRACKING OFF
? SET("EVENTTRACKING")
SET FULLPATH OFF
? SET("FULLPATH")
SET FULLPATH ON
SET HEADINGS OFF
? SET("HEADINGS")
SET HEADINGS ON
SET HELP OFF
? SET("HELP")
SET INTENSITY OFF
? SET("INTENSITY")
SET LOCK ON
? SET("LOCK")
SET LOCK OFF
SET LOGERRORS OFF
? SET("LOGERRORS")
SET MULTILOCKS ON
? SET("MULTILOCKS")
SET MULTILOCKS OFF
SET NOTIFY OFF
? SET("NOTIFY")
SET NULL ON
? SET("NULL")
SET NULL OFF
SET OLEOBJECT OFF
? SET("OLEOBJECT")
SET OPTIMIZE OFF
? SET("OPTIMIZE")
SET OPTIMIZE ON
SET PALETTE OFF
? SET("PALETTE")
SET PRINTER OFF
? SET("PRINTER")
SET READBORDER ON
? SET("READBORDER")
SET RESOURCE OFF
? SET("RESOURCE")
SET SPACE OFF
? SET("SPACE")
SET SPACE ON
SET STATUS ON
? SET("STATUS")
SET STATUS OFF
SET STATUS BAR OFF
? SET("STATUS BAR")
SET SYSFORMATS ON
? SET("SYSFORMATS")
SET SYSFORMATS OFF
SET TRBETWEEN ON
? SET("TRBETWEEN")

* the settings that carry a number rather than a switch
SET BLOCKSIZE TO 128
? TRANSFORM(SET("BLOCKSIZE"))
SET CPCOMPILE TO 1252
? TRANSFORM(SET("CPCOMPILE"))
SET DATASESSION TO 1
? TRANSFORM(SET("DATASESSION"))
SET ENGINEBEHAVIOR 70
? TRANSFORM(SET("ENGINEBEHAVIOR"))
SET ENGINEBEHAVIOR 90
SET MARGIN TO 5
? TRANSFORM(SET("MARGIN"))
SET MARGIN TO 0
SET REFRESH TO 30, 15
? TRANSFORM(SET("REFRESH"))
SET REPROCESS TO 4
? TRANSFORM(SET("REPROCESS"))
SET STRICTDATE TO 2
? TRANSFORM(SET("STRICTDATE"))
SET STRICTDATE TO 1
SET TABLEVALIDATE TO 0
? TRANSFORM(SET("TABLEVALIDATE"))
SET TYPEAHEAD TO 40
? TRANSFORM(SET("TYPEAHEAD"))

* and the ones that carry a word of their own
SET COLLATE TO "GENERAL"
? SET("COLLATE")
SET COLLATE TO "MACHINE"
? SET("COLLATE")
SET DEVICE TO SCREEN
? SET("DEVICE")
* the display mode answers with whatever the screen really is, so it is set and not asked
SET DISPLAY TO VGA25
SET KEYCOMP TO DOS
? SET("KEYCOMP")
SET KEYCOMP TO WINDOWS
SET MACKEY TO F10
? SET("MACKEY")
SET UDFPARMS TO REFERENCE
? SET("UDFPARMS")
SET UDFPARMS TO VALUE
? SET("UDFPARMS")

* the ones that name a file, cleared by naming none
SET CLASSLIB TO
? "[" + SET("CLASSLIB") + "]"
SET COVERAGE TO
? "[" + SET("COVERAGE") + "]"
SET FORMAT TO
? "[" + SET("FORMAT") + "]"
SET LIBRARY TO
? "[" + SET("LIBRARY") + "]"
SET PDSETUP TO
? "[" + SET("PDSETUP") + "]"
SET PROCEDURE TO
? "[" + SET("PROCEDURE") + "]"
SET VIEW OFF

* a setting is put back from what SET() said, which is what makes the round trip worth having
LOCAL cWas
SET DELETED ON
cWas = SET("DELETED")
SET DELETED OFF
SET DELETED &cWas
? SET("DELETED")
SET DELETED OFF
* COVERS: SET ANSI, SET AUTOINCERROR, SET AUTOSAVE, SET BELL, SET BLOCKSIZE, SET BROWSEIME,
* COVERS: SET BRSTATUS, SET CLASSLIB, SET CLEAR, SET CLOCK, SET COLLATE, SET COMPATIBLE,
* COVERS: SET CONFIRM, SET CONSOLE, SET COVERAGE, SET CPCOMPILE, SET CPDIALOG, SET CURSOR,
* COVERS: SET DATASESSION, SET DELIMITERS, SET DEVELOPMENT, SET DEVICE, SET DISPLAY,
* COVERS: SET DOHISTORY, SET ENGINEBEHAVIOR, SET EVENTTRACKING, SET FORMAT, SET FULLPATH,
* COVERS: SET HEADINGS, SET HELP, SET INTENSITY, SET KEYCOMP, SET LIBRARY, SET LOCK,
* COVERS: SET LOGERRORS, SET MACKEY, SET MARGIN, SET MULTILOCKS, SET NOTIFY, SET NULL,
* COVERS: SET OLEOBJECT, SET OPTIMIZE, SET PALETTE, SET PDSETUP, SET PRINTER, SET PROCEDURE,
* COVERS: SET READBORDER, SET REFRESH, SET REPROCESS, SET RESOURCE, SET SPACE, SET STATUS,
* COVERS: SET STATUS BAR, SET STRICTDATE, SET SYSFORMATS, SET TABLEVALIDATE, SET TRBETWEEN,
* COVERS: SET TYPEAHEAD, SET UDFPARMS, SET VIEW
