import type { ObjectDescriptor } from '../types';
import * as c from '../common';

/**
 * The data environment of a form: the tables it opens when it loads, and the relations between
 * them. It is not a control - nothing of it is drawn - but a program reaches it through the form
 * and reads what it holds, so it is described here like everything else.
 */
export const dataenvironment: ObjectDescriptor = {
  displayName: 'Data Environment',
  baseClass: 'dataenvironment',
  defaultEvent: 'BeforeOpenTables',
  properties: c.props(
    c.prop('AutoCloseTables', 'boolean', 'Data', true),
    c.prop('AutoOpenTables', 'boolean', 'Data', true),
    c.prop('InitialSelectedAlias', 'text', 'Data', ''),
    c.prop('OpenViews', 'number', 'Data', 0, { min: 0, max: 2 }),
    c.prop('DataSource', 'text', 'Data', '', { hidden: true }),
    c.enumProp('DataSourceType', 'Data', 0, c.enumValues(['Native', 'ODBC'])),
    c.containerProps,
    c.prop('Comment', 'multiline', 'Other', ''),
    c.prop('Tag', 'text', 'Other', ''),
  ),
  events: c.events(c.baseEvents, [
    c.ev('BeforeOpenTables', ''),
    c.ev('AfterCloseTables', ''),
    c.ev('OpenTables', ''),
    c.ev('CloseTables', ''),
  ]),
};

/** One table of a data environment: how it is opened and how it behaves once it is. */
export const cursor: ObjectDescriptor = {
  displayName: 'Cursor',
  baseClass: 'cursor',
  defaultEvent: 'Init',
  properties: c.props(
    c.prop('Alias', 'text', 'Data', ''),
    c.prop('CursorSource', 'text', 'Data', ''),
    c.prop('Database', 'text', 'Data', ''),
    c.prop('Exclusive', 'boolean', 'Data', false),
    c.prop('Filter', 'expression', 'Data', ''),
    c.prop('NoDataOnLoad', 'boolean', 'Data', false),
    c.prop('NoData', 'boolean', 'Data', false, { hidden: true }),
    c.prop('Order', 'text', 'Data', ''),
    c.prop('OrderDirection', 'text', 'Data', '', { description: 'Which way that order runs: ascending or descending.' }),
    c.prop('Optimize', 'boolean', 'Data', true, { description: 'Whether Rushmore is used on this cursor.' }),
    c.prop('View', 'text', 'Data', '', { readOnly: true, description: 'The view it was filled from, when it came from one.' }),
    c.prop('ReadOnly', 'boolean', 'Data', false),
    c.enumProp('BufferModeOverride', 'Data', 0, c.enumValues(['Use the form', 'None', 'Pessimistic row', 'Optimistic row', 'Pessimistic table', 'Optimistic table'])),
    c.prop('CursorStatus', 'number', 'Data', 0, { readOnly: true, hidden: true }),
    c.prop('CursorSchema', 'text', 'Data', '', { hidden: true }),
    c.prop('UseCursorSchema', 'boolean', 'Data', false),
    c.prop('UseMemoSize', 'number', 'Data', 255, { min: 1 }),
    c.prop('UseDeDataSource', 'boolean', 'Data', true),
    c.prop('AllowSimultaneousFetch', 'boolean', 'Data', false),
    c.prop('BatchUpdateCount', 'number', 'Data', 1, { min: 1 }),
    c.prop('CompareMemo', 'boolean', 'Data', true),
    c.prop('ConflictCheckCmd', 'text', 'Data', '', { hidden: true }),
    c.enumProp('ConflictCheckType', 'Data', 0, c.enumValues(['Key fields', 'Key and updatable', 'Key and modified', 'Key and timestamp'])),
    c.prop('DeleteCmd', 'text', 'Data', '', { hidden: true }),
    c.prop('DeleteCmdDataSource', 'text', 'Data', '', { hidden: true }),
    c.prop('DeleteCmdDataSourceType', 'text', 'Data', '', { hidden: true }),
    c.prop('FetchAsNeeded', 'boolean', 'Data', false),
    c.prop('FetchMemo', 'boolean', 'Data', true),
    c.prop('FetchMemoCmdList', 'text', 'Data', '', { hidden: true }),
    c.prop('FetchMemoDataSource', 'text', 'Data', '', { hidden: true }),
    c.prop('FetchMemoDataSourceType', 'text', 'Data', '', { hidden: true }),
    c.prop('FetchSize', 'number', 'Data', 100),
    c.prop('InsertCmd', 'text', 'Data', '', { hidden: true }),
    c.prop('InsertCmdDataSource', 'text', 'Data', '', { hidden: true }),
    c.prop('InsertCmdDataSourceType', 'text', 'Data', '', { hidden: true }),
    c.prop('InsertCmdRefreshCmd', 'text', 'Data', '', { hidden: true }),
    c.prop('InsertCmdRefreshFieldList', 'text', 'Data', '', { hidden: true }),
    c.prop('InsertCmdRefreshKeyFieldList', 'text', 'Data', '', { hidden: true }),
    c.prop('KeyFieldList', 'text', 'Data', ''),
    c.prop('MaxRecords', 'number', 'Data', -1),
    c.prop('Prepared', 'boolean', 'Data', false),
    c.prop('RefreshAlias', 'text', 'Data', '', { hidden: true }),
    c.prop('RefreshCmd', 'text', 'Data', '', { hidden: true }),
    c.prop('RefreshCmdDataSource', 'text', 'Data', '', { hidden: true }),
    c.prop('RefreshCmdDataSourceType', 'text', 'Data', '', { hidden: true }),
    c.prop('RefreshIgnoreFieldList', 'text', 'Data', '', { hidden: true }),
    c.prop('RefreshTimeStamp', 'boolean', 'Data', false, { hidden: true }),
    c.prop('RespectCursorCP', 'boolean', 'Data', false),
    c.prop('SelectCmd', 'text', 'Data', '', { hidden: true }),
    c.prop('SendUpdates', 'boolean', 'Data', false),
    c.prop('Tables', 'text', 'Data', '', { hidden: true }),
    c.prop('TimestampFieldList', 'text', 'Data', '', { hidden: true }),
    c.prop('UpdatableFieldList', 'text', 'Data', '', { hidden: true }),
    c.prop('UpdateCmd', 'text', 'Data', '', { hidden: true }),
    c.prop('UpdateCmdDataSource', 'text', 'Data', '', { hidden: true }),
    c.prop('UpdateCmdDataSourceType', 'text', 'Data', '', { hidden: true }),
    c.prop('UpdateCmdRefreshCmd', 'text', 'Data', '', { hidden: true }),
    c.prop('UpdateCmdRefreshFieldList', 'text', 'Data', '', { hidden: true }),
    c.prop('UpdateCmdRefreshKeyFieldList', 'text', 'Data', '', { hidden: true }),
    c.prop('UpdateNameList', 'text', 'Data', '', { hidden: true }),
    c.enumProp('UpdateType', 'Data', 1, c.enumValues(['Update the record', 'Delete and insert'], 1)),
    c.prop('UseTransactions', 'boolean', 'Data', false),
    c.enumProp('WhereType', 'Data', 3, c.enumValues(['Key fields only', 'Key and updatable', 'Key and modified', 'Key and timestamp'], 1)),
    c.prop('Comment', 'multiline', 'Other', ''),
    c.prop('Tag', 'text', 'Other', ''),
  ),
  events: c.events(c.baseEvents, [
    c.ev('BeforeCursorAttach', 'cAlias'),
    c.ev('AfterCursorAttach', 'cAlias'),
    c.ev('BeforeCursorClose', 'cAlias'),
    c.ev('AfterCursorClose', 'cAlias'),
    c.ev('BeforeCursorDetach', 'cAlias'),
    c.ev('AfterCursorDetach', 'cAlias'),
    c.ev('BeforeCursorFill', 'lUseCursorSchema, lNoDataOnLoad, cSelectCmd'),
    c.ev('AfterCursorFill', 'lUseCursorSchema, lNoDataOnLoad, cSelectCmd, lResult'),
    c.ev('BeforeCursorRefresh', 'cAlias'),
    c.ev('AfterCursorRefresh', 'cAlias'),
    c.ev('BeforeCursorUpdate', 'cAlias'),
    c.ev('AfterCursorUpdate', 'cAlias'),
    c.ev('BeforeRecordRefresh', 'cAlias'),
    c.ev('AfterRecordRefresh', 'cAlias'),
    c.ev('BeforeInsert', 'cAlias'),
    c.ev('AfterInsert', 'cAlias, nResult'),
    c.ev('BeforeUpdate', 'cAlias'),
    c.ev('AfterUpdate', 'cAlias, nResult'),
    c.ev('BeforeDelete', 'cAlias'),
    c.ev('AfterDelete', 'cAlias, nResult'),
  ]),
};

/** A relation between two cursors of a data environment: what SET RELATION would set. */
export const relation: ObjectDescriptor = {
  displayName: 'Relation',
  baseClass: 'relation',
  defaultEvent: 'Init',
  properties: c.props(
    c.prop('ParentAlias', 'text', 'Data', ''),
    c.prop('ChildAlias', 'text', 'Data', ''),
    c.prop('ChildTable', 'text', 'Data', ''),
    c.prop('ParentTable', 'text', 'Data', '', { hidden: true }),
    c.prop('RelationalExpr', 'expression', 'Data', ''),
    c.prop('OneToMany', 'boolean', 'Data', false),
    c.prop('ChildOrder', 'text', 'Data', ''),
    c.prop('Comment', 'multiline', 'Other', ''),
    c.prop('Tag', 'text', 'Other', ''),
  ),
  events: c.events(c.baseEvents),
};
