import type { ObjectDescriptor } from '../types';
import * as c from '../common';

/** The form itself. Not a ControlDescriptor: it has no toolbox entry and no Left/Top relative to a parent. */
export const form: ObjectDescriptor = {
  displayName: 'Form',
  baseClass: 'form',
  defaultEvent: 'Init',
  properties: c.props(
    c.prop('Caption', 'text', 'Appearance', 'Form1'),
    c.prop('Left', 'number', 'Layout', 0),
    c.prop('Top', 'number', 'Layout', 0),
    c.prop('Width', 'number', 'Layout', 375, { min: 0 }),
    c.prop('Height', 'number', 'Layout', 250, { min: 0 }),
    c.prop('MinWidth', 'number', 'Layout', -1),
    c.prop('MinHeight', 'number', 'Layout', -1),
    c.prop('MaxWidth', 'number', 'Layout', -1),
    c.prop('MaxHeight', 'number', 'Layout', -1),
    c.prop('AutoCenter', 'boolean', 'Layout', false),
    c.enumProp('BorderStyle', 'Appearance', 3, c.enumValues(['None', 'Fixed Single', 'Fixed Dialog', 'Sizable'])),
    c.prop('TitleBar', 'boolean', 'Appearance', true),
    c.prop('ControlBox', 'boolean', 'Appearance', true),
    c.prop('Closable', 'boolean', 'Behavior', true),
    c.prop('Sizable', 'boolean', 'Behavior', true, { description: 'Whether the user may change how big it is.' }),
    // what a READ in a form converted from FoxPro 2.x was told to do
    c.prop('ReadCycle', 'boolean', 'Behavior', false, { description: 'Whether the fields are walked round and round rather than left at the end.' }),
    c.prop('ReadLock', 'boolean', 'Behavior', false, { description: 'Whether the record is locked while it is being read.' }),
    c.prop('ReadMouse', 'boolean', 'Behavior', true, { description: 'Whether the mouse may move between the fields.' }),
    c.prop('ReadObject', 'number', 'Behavior', 0, { description: 'Which field the read starts in.' }),
    c.prop('ReadSave', 'boolean', 'Behavior', false, { description: 'Whether what was read is left on the screen after.' }),
    c.prop('ReadTimeout', 'number', 'Behavior', 0, { description: 'How long the read waits before it gives up, in seconds.' }),
    c.prop('TerminateRead', 'boolean', 'Behavior', false, { description: 'Set to end the read from inside one of its own methods.' }),
    c.prop('MaxButton', 'boolean', 'Appearance', true),
    c.prop('MinButton', 'boolean', 'Appearance', true),
    c.prop('Movable', 'boolean', 'Behavior', true),
    c.prop('AlwaysOnTop', 'boolean', 'Behavior', false),
    c.prop('Desktop', 'boolean', 'Behavior', false),
    c.enumProp('WindowType', 'Behavior', 0, c.enumValues(['Modeless', 'Modal'])),
    c.enumProp('WindowState', 'Behavior', 0, c.enumValues(['Normal', 'Minimized', 'Maximized'])),
    c.enumProp('ShowWindow', 'Behavior', 0, c.enumValues(['In Screen', 'In Top-Level Form', 'As Top-Level Form'])),
    c.prop('ShowTips', 'boolean', 'Behavior', false),
    c.prop('Icon', 'picture', 'Appearance', ''),
    c.prop('Picture', 'picture', 'Appearance', ''),
    c.enumProp('ScaleMode', 'Layout', 3, [
      { value: 0, label: '0 - Foxels' },
      { value: 3, label: '3 - Pixels' },
    ]),
    c.enumProp('DataSession', 'Data', 1, c.enumValues(['Default Data Session', 'Private Data Session'], 1)),
    c.themesProp,
    c.prop('KeyPreview', 'boolean', 'Behavior', false),
    c.prop('LockScreen', 'boolean', 'Behavior', false),
    c.prop('ActiveControl', 'text', 'Other', '', { readOnly: true, hidden: true, description: 'The control with the focus' }),
    c.prop('AllowOutput', 'boolean', 'Behavior', true),
    c.prop('AlwaysOnBottom', 'boolean', 'Behavior', false),
    c.prop('AutoRelease', 'boolean', 'Behavior', true),
    c.prop('BindControls', 'boolean', 'Data', true),
    c.enumProp('BufferMode', 'Data', 0, c.enumValues(['None', 'Pessimistic', 'Optimistic'])),
    c.prop('ClipControls', 'boolean', 'Appearance', false),
    c.enumProp('ColorSource', 'Appearance', 4, c.enumValues([
      'Object colour properties',
      'Object colour scheme',
      'Form colour scheme',
      'Form colour properties',
      'Windows control panel',
      'Windows 3D colours',
    ])),
    c.prop('ColorScheme', 'number', 'Appearance', 1, { min: 1 }),
    c.prop('ContinuousScroll', 'boolean', 'Behavior', true),
    c.prop('CurrentDataSession', 'number', 'Data', 1, { readOnly: true, hidden: true }),
    c.prop('DataSessionID', 'number', 'Data', 1, { readOnly: true, hidden: true }),
    c.prop('DEClass', 'text', 'Data', ''),
    c.prop('DEClassLibrary', 'text', 'Data', ''),
    c.prop('ErrorNo', 'number', 'Other', 0, { readOnly: true, hidden: true }),
    c.prop('HalfHeightCaption', 'boolean', 'Appearance', false),
    c.prop('HScrollSmallChange', 'number', 'Behavior', 10, { min: 0 }),
    c.prop('VScrollSmallChange', 'number', 'Behavior', 10, { min: 0 }),
    c.prop('MaxLeft', 'number', 'Layout', 0),
    c.prop('MaxTop', 'number', 'Layout', 0),
    c.prop('MDIForm', 'boolean', 'Behavior', false),
    c.prop('OpenWindow', 'boolean', 'Behavior', false),
    c.enumProp('ReleaseType', 'Other', 0, c.enumValues(['Released by the program', 'Closed by the user', 'Closed by Windows']), undefined),
    c.enumProp('ScrollBars', 'Appearance', 0, c.enumValues(['None', 'Horizontal', 'Vertical', 'Both'])),
    c.prop('ShowInTaskbar', 'boolean', 'Appearance', true),
    c.prop('SizeBox', 'boolean', 'Appearance', false),
    c.prop('ViewPortHeight', 'number', 'Layout', 0, { readOnly: true, hidden: true }),
    c.prop('ViewPortWidth', 'number', 'Layout', 0, { readOnly: true, hidden: true }),
    c.prop('ViewPortLeft', 'number', 'Layout', 0, { hidden: true }),
    c.prop('ViewPortTop', 'number', 'Layout', 0, { hidden: true }),
    c.prop('WhatsThisButton', 'boolean', 'Appearance', false),
    c.prop('WhatsThisHelp', 'boolean', 'Behavior', false),
    c.prop('ZoomBox', 'boolean', 'Appearance', false),
    c.drawingProps,
    c.containerProps,
    c.fontProps,
    c.fontExtraProps,
    c.prop('BackColor', 'color', 'Appearance', c.COLOR_BUTTONFACE),
    c.prop('ForeColor', 'color', 'Appearance', c.COLOR_BLACK),
    c.prop('Enabled', 'boolean', 'Behavior', true),
    c.prop('Visible', 'boolean', 'Behavior', false),
    c.prop('HelpContextID', 'number', 'Other', 0),
    c.prop('Comment', 'multiline', 'Other', ''),
    c.prop('Tag', 'text', 'Other', ''),
  ),
  events: c.events(c.baseEvents, c.mouseEvents, c.dragEvents, [
    c.ev('Load', ''),
    c.ev('Unload', ''),
    c.ev('QueryUnload', ''),
    c.ev('Activate', ''),
    c.ev('Deactivate', ''),
    c.ev('Show', 'nStyle'),
    c.ev('Hide', ''),
    c.ev('Resize', ''),
    c.ev('Moved', ''),
    c.ev('Paint', ''),
    c.ev('GotFocus', ''),
    c.ev('LostFocus', ''),
    c.ev('KeyPress', 'nKeyCode, nShiftAltCtrl'),
    c.ev('Scrolled', 'nDirection'),
    c.ev('AdjustObjectSize', 'nIndex, oObject'),
  ]),
};

/**
 * A form set: the container a FoxPro 2.x screen set became, holding forms rather than controls.
 *
 * It is not a window itself - what is on screen is the forms in it - so nothing here is drawn.
 * The READ properties are the ones a converted screen was told to honour; the product keeps them
 * on the set, and the form beside them has its own.
 */
export const formset: ObjectDescriptor = {
  displayName: 'FormSet',
  baseClass: 'formset',
  defaultEvent: 'Init',
  properties: c.props(
    c.prop('ActiveForm', 'text', 'Other', '', { readOnly: true, description: 'The form of the set that has the focus.' }),
    c.prop('AutoRelease', 'boolean', 'Behavior', false, { description: 'Whether the set goes away once its last form has.' }),
    c.prop('FormCount', 'number', 'Other', 0, { readOnly: true }),
    c.prop('Forms', 'text', 'Other', '', { readOnly: true, description: 'The forms in it, by number.' }),
    c.prop('WindowList', 'text', 'Other', '', { description: 'The windows a converted screen set named.' }),
    c.enumProp('WindowType', 'Behavior', 0, c.enumValues(['Modeless', 'Modal'])),
    c.prop('ReadCycle', 'boolean', 'Behavior', true, { description: 'Whether the fields are walked round and round rather than left at the end.' }),
    c.prop('ReadLock', 'boolean', 'Behavior', true, { description: 'Whether the record is locked while it is being read.' }),
    c.prop('ReadMouse', 'boolean', 'Behavior', true, { description: 'Whether the mouse may move between the fields.' }),
    c.prop('ReadSave', 'boolean', 'Behavior', false, { description: 'Whether what was read is left on the screen after.' }),
    c.prop('ReadTimeout', 'number', 'Behavior', 0, { description: 'How long the read waits before it gives up, in seconds; 0 waits for ever.' }),
  ),
  events: c.events([
    c.ev('Init', ''),
    c.ev('Destroy', ''),
    c.ev('Load', ''),
    c.ev('Unload', ''),
    c.ev('Activate', ''),
    c.ev('Deactivate', ''),
    c.ev('Error', 'nError, cMethod, nLine'),
    c.ev('ReadActivate', ''),
    c.ev('ReadDeactivate', ''),
    c.ev('ReadShow', ''),
    c.ev('ReadValid', ''),
    c.ev('ReadWhen', ''),
  ]),
};
