import type { ControlDescriptor } from '../types';
import * as c from '../common';

/** What a grid column changes as it draws each row: the expression each one is worked out by. */
const dynamicProps = [
  c.prop('DynamicAlignment', 'expression', 'Appearance', ''),
  c.prop('DynamicBackColor', 'expression', 'Appearance', ''),
  c.prop('DynamicForeColor', 'expression', 'Appearance', ''),
  c.prop('DynamicCurrentControl', 'expression', 'Data', ''),
  c.prop('DynamicFontName', 'expression', 'Appearance', ''),
  c.prop('DynamicFontOutline', 'expression', 'Appearance', ''),
  c.prop('DynamicFontShadow', 'expression', 'Appearance', ''),
  c.prop('DynamicFontSize', 'expression', 'Appearance', ''),
  c.prop('DynamicFontBold', 'expression', 'Appearance', ''),
  c.prop('DynamicFontItalic', 'expression', 'Appearance', ''),
  c.prop('DynamicFontStrikethru', 'expression', 'Appearance', ''),
  c.prop('DynamicFontUnderline', 'expression', 'Appearance', ''),
  c.prop('DynamicInputMask', 'expression', 'Data', ''),
  c.prop('DynamicLineHeight', 'expression', 'Layout', ''),
];

export const grid: ControlDescriptor = {
  type: 'Grid',
  baseClass: 'grid',
  displayName: 'Grid',
  toolboxGroup: 'Data',
  icon: 'Table',
  namePrefix: 'Grid',
  defaultSize: { Width: 320, Height: 200 },
  defaultEvent: 'AfterRowColChange',
  container: { accepts: ['Column'], autoChildren: { type: 'Column', count: 1, countProp: 'ColumnCount' } },
  properties: c.props(
    c.layoutProps(320, 200),
    c.prop('ColumnCount', 'number', 'Layout', 1, { min: -1 }),
    c.prop('RecordSource', 'expression', 'Data', ''),
    c.enumProp('RecordSourceType', 'Data', 1, c.enumValues(['Table', 'Alias', 'Prompt', 'Query (.qpr)', 'SQL Statement'])),
    c.prop('HeaderHeight', 'number', 'Layout', 17, { min: 0 }),
    c.prop('RowHeight', 'number', 'Layout', 17, { min: 0 }),
    c.enumProp('GridLines', 'Appearance', 3, c.enumValues(['None', 'Horizontal', 'Vertical', 'Both'])),
    c.prop('GridLineColor', 'color', 'Appearance', 0xc0c0c0),
    c.enumProp('ScrollBars', 'Appearance', 3, c.enumValues(['None', 'Horizontal', 'Vertical', 'Both'])),
    c.prop('DeleteMark', 'boolean', 'Appearance', true),
    c.prop('RecordMark', 'boolean', 'Appearance', true),
    c.prop('AllowAddNew', 'boolean', 'Behavior', false),
    c.prop('AllowRowSizing', 'boolean', 'Behavior', true),
    c.prop('AllowHeaderSizing', 'boolean', 'Behavior', true),
    c.prop('AllowCellSelection', 'boolean', 'Behavior', true),
    c.prop('ReadOnly', 'boolean', 'Behavior', false),
    c.prop('LockColumns', 'number', 'Behavior', 0, { min: 0 }),
    c.enumProp(
      'HighlightStyle',
      'Appearance',
      0,
      c.enumValues(['No Highlighting', 'Highlight Current Row', 'Highlight Current Row Always']),
      'Whether the current row is highlighted, and whether the highlight persists without focus',
    ),
    c.prop('HighlightBackColor', 'color', 'Appearance', c.COLOR_HIGHLIGHT),
    c.prop('HighlightForeColor', 'color', 'Appearance', c.COLOR_HIGHLIGHT_TEXT),
    c.selectedItemColorProps,
    c.prop('LinkMaster', 'expression', 'Data', ''),
    c.prop('ChildOrder', 'expression', 'Data', ''),
    c.prop('RelationalExpr', 'expression', 'Data', ''),
    c.prop('ActiveColumn', 'number', 'Data', 0, { readOnly: true, hidden: true }),
    c.prop('ActiveRow', 'number', 'Data', 0, { readOnly: true, hidden: true }),
    c.prop('RelativeColumn', 'number', 'Data', 0, { readOnly: true, hidden: true }),
    c.prop('RelativeRow', 'number', 'Data', 0, { readOnly: true, hidden: true }),
    c.prop('LeftColumn', 'number', 'Data', 1, { hidden: true }),
    c.prop('Columns', 'text', 'Data', '', { readOnly: true, hidden: true, description: 'The columns, by position' }),
    c.prop('AllowAutoColumnFit', 'number', 'Behavior', 2, { min: 0, max: 2 }),
    c.prop('AllowDelete', 'boolean', 'Behavior', true),
    c.prop('AllowInsert', 'boolean', 'Behavior', true),
    c.prop('AllowUpdate', 'boolean', 'Behavior', true),
    c.prop('ContinuousScroll', 'boolean', 'Behavior', true),
    c.prop('GridLineWidth', 'number', 'Appearance', 1, { min: 1 }),
    c.prop('Highlight', 'boolean', 'Appearance', true),
    c.prop('HighlightRow', 'boolean', 'Appearance', true),
    c.prop('HighlightRowLineWidth', 'number', 'Appearance', 1, { min: 0 }),
    c.prop('LockColumnsLeft', 'number', 'Behavior', 0, { min: 0 }),
    c.prop('Partition', 'number', 'Layout', 0, { min: 0 }),
    c.prop('SplitBar', 'boolean', 'Appearance', true),
    c.prop('RowColChange', 'number', 'Data', 0, { readOnly: true, hidden: true }),
    c.prop('ColumnWidths', 'text', 'Layout', '', { hidden: true }),
    c.memberClassProps,
    c.themesProp,
    c.enumProp('BorderStyle', 'Appearance', 1, c.enumValues(['None', 'Fixed Single'])),
    c.fontProps,
    c.colorProps(),
    c.behaviorProps,
    c.tabProps,
  ),
  events: c.events(c.baseEvents, c.mouseEvents, c.focusEvents, c.dragEvents, [
    c.ev('AfterRowColChange', 'nColIndex'),
    c.ev('BeforeRowColChange', 'nColIndex'),
    c.ev('Deleted', ''),
    c.ev('Scrolled', 'nDirection'),
  ]),
};

export const column: ControlDescriptor = {
  type: 'Column',
  baseClass: 'column',
  displayName: 'Column',
  toolboxGroup: 'Data',
  icon: 'TableSimple',
  namePrefix: 'Column',
  hideInToolbox: true,
  defaultSize: { Width: 75, Height: 17 },
  // a Column has no Click of its own - the product's member list says so - so the event the
  // designer opens on a double-click is the one it does run
  defaultEvent: 'Init',
  container: { accepts: ['Header'], autoChildren: { type: 'Header', count: 1 } },
  properties: c.props(
    c.prop('Width', 'number', 'Layout', 75, { min: 0 }),
    c.prop('ColumnOrder', 'number', 'Layout', 1, { min: 1 }),
    c.prop('ControlSource', 'expression', 'Data', ''),
    c.prop('CurrentControl', 'text', 'Data', 'Text1', { description: 'Name of the contained control that displays and edits the cell' }),
    c.prop('Bound', 'boolean', 'Data', true),
    c.prop('HeaderClass', 'text', 'Other', ''),
    c.prop('HeaderClassLibrary', 'text', 'Other', ''),
    c.prop('ReadOnly', 'boolean', 'Behavior', false),
    c.prop('Resizable', 'boolean', 'Behavior', true),
    c.prop('Movable', 'boolean', 'Behavior', true),
    c.prop('Sparse', 'boolean', 'Behavior', true),
    dynamicProps,
    c.alignmentProp(3, true),
    c.prop('Format', 'text', 'Data', ''),
    c.prop('InputMask', 'text', 'Data', ''),
    c.fontProps,
    c.colorProps(),
    c.prop('Enabled', 'boolean', 'Behavior', true),
    c.prop('Visible', 'boolean', 'Behavior', true),
    c.prop('Comment', 'multiline', 'Other', ''),
    c.prop('Tag', 'text', 'Other', ''),
  ),
  events: c.events(c.baseEvents, c.mouseEvents, c.focusEvents, c.dragEvents),
};

export const header: ControlDescriptor = {
  type: 'Header',
  baseClass: 'header',
  displayName: 'Header',
  toolboxGroup: 'Data',
  icon: 'TextHeader1',
  namePrefix: 'Header',
  hideInToolbox: true,
  defaultSize: { Width: 75, Height: 17 },
  defaultEvent: 'Click',
  properties: c.props(
    c.prop('Caption', 'text', 'Appearance', 'Header1'),
    c.alignmentProp(2),
    c.prop('Picture', 'picture', 'Appearance', ''),
    c.prop('WordWrap', 'boolean', 'Appearance', false),
    c.fontProps,
    c.colorProps(c.COLOR_BUTTONFACE),
    c.prop('Comment', 'multiline', 'Other', ''),
    c.prop('Tag', 'text', 'Other', ''),
  ),
  events: c.events(c.baseEvents, c.mouseEvents, c.dragEvents),
};
