import type { ControlDescriptor } from '../types';
import * as c from '../common';

export const optiongroup: ControlDescriptor = {
  type: 'OptionGroup',
  baseClass: 'optiongroup',
  displayName: 'Option Group',
  toolboxGroup: 'Standard',
  icon: 'RadioButton',
  namePrefix: 'Optiongroup',
  defaultSize: { Width: 100, Height: 50 },
  defaultEvent: 'Click',
  container: { accepts: ['OptionButton'], autoChildren: { type: 'OptionButton', count: 2, countProp: 'ButtonCount' } },
  properties: c.props(
    c.layoutProps(100, 50),
    c.prop('ButtonCount', 'number', 'Layout', 2, { min: 0, max: 99 }),
    c.prop('ControlSource', 'expression', 'Data', ''),
    c.prop('Value', 'number', 'Data', 1, { min: 0 }),
    c.prop('AutoSize', 'boolean', 'Layout', false),
    c.backStyleProp,
    c.enumProp('BorderStyle', 'Appearance', 1, c.enumValues(['None', 'Fixed Single'])),
    c.specialEffectProp,
    c.memberClassProps,
    c.themesProp,
    c.fontProps,
    c.colorProps(c.COLOR_BUTTONFACE),
    c.containerProps,
    c.prop('Buttons', 'text', 'Other', '', { readOnly: true, hidden: true, description: 'The buttons, by position' }),
    c.behaviorProps,
    c.tabProps,
  ),
  events: c.events(c.baseEvents, c.mouseEvents, c.focusEvents, c.changeEvents, c.dragEvents),
};

export const optionbutton: ControlDescriptor = {
  type: 'OptionButton',
  baseClass: 'optionbutton',
  displayName: 'Option Button',
  toolboxGroup: 'Standard',
  icon: 'RadioButton',
  namePrefix: 'Option',
  hideInToolbox: true,
  defaultSize: { Width: 80, Height: 17 },
  defaultEvent: 'Click',
  properties: c.props(
    c.layoutProps(80, 17),
    c.prop('Caption', 'text', 'Appearance', 'Option1'),
    c.prop('Value', 'number', 'Data', 0, { min: 0, max: 1 }),
    c.alignmentProp(0),
    c.prop('AutoSize', 'boolean', 'Layout', false),
    c.enumProp('Style', 'Appearance', 0, c.enumValues(['Standard', 'Graphical'])),
    c.prop('Picture', 'picture', 'Appearance', ''),
    c.prop('DownPicture', 'picture', 'Appearance', ''),
    c.prop('DisabledPicture', 'picture', 'Appearance', ''),
    c.picturePositionProp,
    c.themesProp,
    c.backStyleProp,
    c.fontProps,
    c.colorProps(c.COLOR_BUTTONFACE),
    c.behaviorProps,
  ),
  events: c.events(c.baseEvents, c.mouseEvents, c.focusEvents, c.dragEvents),
};
