import type { ControlDescriptor } from '../types';
import * as c from '../common';

export const pageframe: ControlDescriptor = {
  type: 'PageFrame',
  baseClass: 'pageframe',
  displayName: 'Page Frame',
  toolboxGroup: 'Container',
  icon: 'TabDesktop',
  namePrefix: 'Pageframe',
  defaultSize: { Width: 250, Height: 200 },
  defaultEvent: 'Click',
  container: { accepts: ['Page'], autoChildren: { type: 'Page', count: 2, countProp: 'PageCount' } },
  properties: c.props(
    c.layoutProps(250, 200),
    c.prop('PageCount', 'number', 'Layout', 2, { min: 0, max: 99 }),
    c.prop('ActivePage', 'number', 'Behavior', 1, { min: 1 }),
    c.prop('Tabs', 'boolean', 'Appearance', true),
    c.enumProp('TabStyle', 'Appearance', 0, c.enumValues(['Justified', 'Nonjustified'])),
    c.enumProp('TabOrientation', 'Appearance', 0, c.enumValues(['Top', 'Bottom', 'Left', 'Right'])),
    c.prop('TabStretch', 'number', 'Appearance', 1, { min: 0, max: 1 }),
    c.enumProp('BorderStyle', 'Appearance', 1, c.enumValues(['None', 'Fixed Single'])),
    c.prop('BorderWidth', 'number', 'Appearance', 1, { min: 0 }),
    c.memberClassProps,
    c.themesProp,
    c.fontProps,
    c.containerProps,
    c.prop('Pages', 'text', 'Other', '', { readOnly: true, hidden: true, description: 'The pages, by position' }),
    c.behaviorProps,
    c.tabProps,
  ),
  events: c.events(c.baseEvents, c.mouseEvents, c.dragEvents),
};

export const page: ControlDescriptor = {
  type: 'Page',
  baseClass: 'page',
  displayName: 'Page',
  toolboxGroup: 'Container',
  icon: 'Document',
  namePrefix: 'Page',
  hideInToolbox: true,
  defaultSize: { Width: 250, Height: 176 },
  defaultEvent: 'Activate',
  container: { accepts: 'visual' },
  properties: c.props(
    c.prop('Caption', 'text', 'Appearance', 'Page1'),
    c.prop('PageOrder', 'number', 'Layout', 1, { min: 1 }),
    c.prop('Picture', 'picture', 'Appearance', ''),
    c.prop('StatusBarText', 'text', 'Behavior', ''),
    c.fontProps,
    c.colorProps(c.COLOR_BUTTONFACE),
    c.prop('Enabled', 'boolean', 'Behavior', true),
    c.prop('ToolTipText', 'text', 'Behavior', ''),
    c.prop('Comment', 'multiline', 'Other', ''),
    c.prop('Tag', 'text', 'Other', ''),
  ),
  events: c.events(c.baseEvents, c.mouseEvents, c.dragEvents, [c.ev('Activate', ''), c.ev('Deactivate', '')]),
};
