import type { ControlDescriptor } from '../types';
import * as c from '../common';

export const textbox: ControlDescriptor = {
  type: 'TextBox',
  baseClass: 'textbox',
  displayName: 'Text Box',
  toolboxGroup: 'Standard',
  icon: 'TextField',
  namePrefix: 'Text',
  defaultSize: { Width: 100, Height: 23 },
  defaultEvent: 'InteractiveChange',
  properties: c.props(
    c.layoutProps(100, 23),
    c.dataProps,
    c.prop('InputMask', 'text', 'Data', ''),
    c.prop('Format', 'text', 'Data', ''),
    c.prop('MaxLength', 'number', 'Data', 0, { min: 0 }),
    c.prop('PasswordChar', 'text', 'Appearance', ''),
    c.prop('ReadOnly', 'boolean', 'Behavior', false),
    c.prop('SelectOnEntry', 'boolean', 'Behavior', false),
    c.alignmentProp(3, true),
    c.borderStyleProp,
    c.specialEffectProp,
    c.prop('Margin', 'number', 'Appearance', 2, { min: 0 }),
    c.prop('StatusBarText', 'text', 'Behavior', ''),
    c.prop('EnableHyperlinks', 'boolean', 'Behavior', false, { description: 'Displays URLs in the text as clickable hyperlinks' }),
    c.themesProp,
    c.editingProps,
    c.dateEntryProps,
    c.fontProps,
    c.fontExtraProps,
    c.colorProps(),
    c.selectedTextColorProps,
    c.behaviorProps,
    c.tabProps,
  ),
  events: c.events(c.baseEvents, c.mouseEvents, c.focusEvents, c.changeEvents, c.dragEvents, [c.ev('RangeHigh', ''), c.ev('RangeLow', '')]),
};
