import type { FC } from 'react';
import {
  AppsListRegular,
  ArrowSortRegular,
  BracesRegular,
  ButtonRegular,
  CodeRegular,
  CubeRegular,
  CheckboxCheckedRegular,
  ChevronDownRegular,
  CursorRegular,
  DatabaseRegular,
  DividerTallRegular,
  DocumentRegular,
  GroupRegular,
  ImageRegular,
  KeyRegular,
  LineRegular,
  LinkRegular,
  PuzzlePieceRegular,
  RadioButtonRegular,
  SquareRegular,
  TabDesktopRegular,
  TableRegular,
  TableSimpleRegular,
  TextBulletListRegular,
  TextBulletListSquareRegular,
  TextFieldRegular,
  TextHeader1Regular,
  TextTRegular,
  TimerRegular,
  ToolboxRegular,
  WindowRegular,
} from '@fluentui/react-icons';

const ICONS: Record<string, FC> = {
  AppsList: AppsListRegular,
  ArrowSort: ArrowSortRegular,
  Braces: BracesRegular,
  Button: ButtonRegular,
  Code: CodeRegular,
  Cube: CubeRegular,
  CheckboxChecked: CheckboxCheckedRegular,
  ChevronDown: ChevronDownRegular,
  Cursor: CursorRegular,
  Database: DatabaseRegular,
  DividerTall: DividerTallRegular,
  Document: DocumentRegular,
  Group: GroupRegular,
  Image: ImageRegular,
  Key: KeyRegular,
  Line: LineRegular,
  Link: LinkRegular,
  PuzzlePiece: PuzzlePieceRegular,
  RadioButton: RadioButtonRegular,
  Square: SquareRegular,
  TabDesktop: TabDesktopRegular,
  Table: TableRegular,
  TableSimple: TableSimpleRegular,
  TextBulletList: TextBulletListRegular,
  TextBulletListSquare: TextBulletListSquareRegular,
  TextField: TextFieldRegular,
  TextHeader1: TextHeader1Regular,
  TextT: TextTRegular,
  Timer: TimerRegular,
  Toolbox: ToolboxRegular,
  Window: WindowRegular,
};

/** Resolves a descriptor icon name to a Fluent icon component. */
export function resolveIcon(name: string): FC {
  return ICONS[name] ?? SquareRegular;
}
