// Builds crates/foxvm to wasm and inlines the module as base64 so the renderer can
// instantiate it without fetch (production loads over file://, tests run in jsdom).
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outDir = join(root, 'src', 'wasm', 'foxvm', 'generated');
const wasmPack = join(root, 'node_modules', 'wasm-pack', 'binary', process.platform === 'win32' ? 'wasm-pack.exe' : 'wasm-pack');

const args = ['build', 'crates/foxvm', '--target', 'web', '--release', '--no-pack', '--out-dir', outDir, '--out-name', 'foxvm', '--', '--features', 'wasm'];
const r = spawnSync(wasmPack, args, { cwd: root, stdio: 'inherit' });
if (r.error) {
  console.error(`[build-wasm] failed to run ${wasmPack}: ${r.error.message}`);
  process.exit(1);
}
if (r.status !== 0) process.exit(r.status ?? 1);

const wasm = readFileSync(join(outDir, 'foxvm_bg.wasm'));
writeFileSync(
  join(outDir, 'foxvm_wasm.ts'),
  `// generated by scripts/build-wasm.mjs, do not edit\nexport const FOXVM_WASM_B64 =\n  '${wasm.toString('base64')}';\n`,
);
rmSync(join(outDir, '.gitignore'), { force: true });
console.log(`[build-wasm] ${(wasm.length / 1024).toFixed(0)} KB wasm inlined into ${outDir}`);
